### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by jericopulvera** [ratiw/vuetable-2#34]
> vuetable-2@1.0.3 dev /home/eco/Downloads/vuetable-2-master
> node build/dev-server.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Function.listen (/home/eco/Downloads/vuetable-2-master/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/home/eco/Downloads/vuetable-2-master/build/dev-server.js:59:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dev"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! vuetable-2@1.0.3 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuetable-2@1.0.3 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vuetable-2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vuetable-2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vuetable-2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eco/Downloads/vuetable-2-master/npm-debug.log

**Comment by ratiw** [comment]
@jericopulvera You probably run something that uses port 8080. Exit that other app and try again

```
Error: listen EADDRINUSE :::8080
```
