### ISSUE TITLE
ReferenceError: document is not defined Nuxtjs

### ISSUE THREAD

**Issue by shijiezhou1** [ratiw/vuetable-2#705]
I'm getting error when using nuxtjs on build

2:34:22 PM: ReferenceError: document is not defined
2:34:22 PM:     at o (/opt/build/repo/node_modules/vuetable-2/dist/vuetable-2.js:1:7155)
2:34:22 PM:     at r (/opt/build/repo/node_modules/vuetable-2/dist/vuetable-2.js:1:6986)
2:34:22 PM:     at t.exports (/opt/build/repo/node_modules/vuetable-2/dist/vuetable-2.js:1:8609)
2:34:22 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/vuetable-2/dist/vuetable-2.js:1:77936)
2:34:22 PM:     at e (/opt/build/repo/node_modules/vuetable-2/dist/vuetable-2.js:1:382)
2:34:22 PM:     at a.r (/opt/build/repo/node_modules/vuetable-2/dist/vuetable-2.js:1:23865)
2:34:22 PM:     at Ft (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:11191)
2:34:22 PM:     at Ze (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:25133)
2:34:22 PM:     at a.e._init (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:32564)
2:34:22 PM:     at new a (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
2:34:22 PM:     at Vi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:66341)
2:34:22 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70571)
2:34:22 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70244)
2:34:22 PM:     at _t.eo [as renderNode] (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67491)
2:34:22 PM:     at _t.next (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:20507)
2:34:22 PM:     at n (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:18719)
2:34:22 PM: ​
2:34:22 PM: (build.command completed in 49.1s)

**Comment by shijiezhou1** [comment]
Please do help to solve this issue.
